// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzwyYY8VSEKkOzT-ibzXQoH2F-5xxa0vo',
    appId: '1:597252859931:web:2a64cf0ac371c3f374f0be',
    messagingSenderId: '597252859931',
    projectId: 'authtutorial-84e63',
    authDomain: 'authtutorial-84e63.firebaseapp.com',
    storageBucket: 'authtutorial-84e63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq8jz6Ed63tSp1Mk7hfBnF1gPuUXOpBcY',
    appId: '1:597252859931:android:6c350a3b2454816774f0be',
    messagingSenderId: '597252859931',
    projectId: 'authtutorial-84e63',
    storageBucket: 'authtutorial-84e63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwxpFU9boDQ1oH64zv4k9wYePnOpjpJc',
    appId: '1:597252859931:ios:d4a9d6ddf7bc95da74f0be',
    messagingSenderId: '597252859931',
    projectId: 'authtutorial-84e63',
    storageBucket: 'authtutorial-84e63.firebasestorage.app',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIwxpFU9boDQ1oH64zv4k9wYePnOpjpJc',
    appId: '1:597252859931:ios:d4a9d6ddf7bc95da74f0be',
    messagingSenderId: '597252859931',
    projectId: 'authtutorial-84e63',
    storageBucket: 'authtutorial-84e63.firebasestorage.app',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzwyYY8VSEKkOzT-ibzXQoH2F-5xxa0vo',
    appId: '1:597252859931:web:615b3d6311600c6d74f0be',
    messagingSenderId: '597252859931',
    projectId: 'authtutorial-84e63',
    authDomain: 'authtutorial-84e63.firebaseapp.com',
    storageBucket: 'authtutorial-84e63.firebasestorage.app',
  );
}
